version: "3"

services:
    php:
        image: php:8.3-apache
        container_name: php
        volumes:
            - ./src/:/var/www/html/
            - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf

    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - MYSQL_DATABASE=db
            - MYSQL_USER=sqluser
            - MYSQL_PASSWORD=azerty
        volumes:
            - dbdata:/var/lib/mysql
            - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        volumes:
            - ./conf/phpmyadmin.apache.conf:/etc/apache2/conf-enabled/server-name.conf

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/reverse.conf
            - ./cert/www.supersite.com.crt:/etc/nginx/ssl/www.supersite.com.crt
            - ./cert/www.supersite.com.key:/etc/nginx/ssl/www.supersite.com.key
            - ./cert/pma.supersite.com.crt:/etc/nginx/ssl/pma.supersite.com.crt
            - ./cert/pma.supersite.com.key:/etc/nginx/ssl/pma.supersite.com.key
        depends_on:
            - php
            - phpmyadmin

volumes:
    dbdata:
