version: "3"

services:
    php:
        image: php:8.3-apache
        ports: 
            - "80:80"
        volumes:
            - ./src/:/var/www/html/
            - ./conf/apache.conf:/etc/apache2/sites-available/000-default.conf

    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - MYSQL_DATABASE=db
            - MYSQL_USER=sqluser
            - MYSQL_PASSWORD=azerty
        volumes:
          - ./sql:/var/lib/mysql
                   
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        volumes:
            - ./conf/phpmyadmin.apache.conf:/etc/apache2/conf-enabled/server-name.conf

    nginx:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - phpmyadmin