# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = [
  { name: "node4.tp3.b2", ip: "10.3.1.11" },
  { name: "node2.tp3.b2", ip: "10.3.1.12" },
  { name: "node3.tp3.b2", ip: "10.3.1.13" }
]

Vagrant.configure("2") do |config|
  
  config.vm.box = "../../super_box.box"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  vms.each do |vm|
    config.vm.define vm[:name] do |node|
      node.vm.hostname = vm[:name]

      # node.vm.network "private_network", name: "VirtualBox Host-Only Ethernet Adapter #4", type: "static", ip: vm[:ip] 
      node.vm.network "private_network", type: "static", ip: vm[:ip]
      node.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
      node.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true
    end
  end
end
